#!/bin/bash

set -xeu

email_address="${1}"
quarantine_dir="${2}"
logs_dir="${3}"
file_to_scan_path="${4}"

file_to_scan_name="$(basename "${file_to_scan_path}")"
log_file="${logs_dir}/${file_to_scan_name}_scan.log"

echo "Processing file ${file_to_scan_name}" > "${log_file}"
clamscan -ir --heuristic-alerts=yes --scan-archive=yes --max-filesize=2000M --max-scansize=2000M "${file_to_scan_path}" >> "${log_file}" || true

infected_files=$(cat "${log_file}" | sed -ne 's/^Infected files: //p')

echo "" >> "${log_file}"

if [[ "${infected_files}" -gt 0 ]]; then
  echo "Moving infected file ${file_to_scan_name} to ${quarantine_dir}" >> "${log_file}"
  mv "${file_to_scan_path}" "${quarantine_dir}"/

  mail -s "Virus detected in qBittorrent file ${file_to_scan_name}" "${email_address}" < "${log_file}"
else
  echo "File ${file_to_scan_name} is clean" >> "${log_file}"
  mail -s "qBittorrent completed file ${file_to_scan_name}" "${email_address}" < "${log_file}"
fi

echo "Email sent to ${email_address}" >> "${log_file}"
